//Project 1 Table


CREATE TABLE DEPARTMENT
(
  NAME  CHAR(15)  NOT NULL,
  LOCATION  VARCHAR(30),
  MANAGER_NUM CHAR(15) NOT NULL,
  STARTDATE DATE,
  PRIMARY KEY (NAME, MANAGER_NUM)
);

CREATE TABLE DEPT_LOCATIONS
(
  LOCATION VARCHAR(30)  NOT NULL,
  PRIMARY KEY (LOCATION)
);

CREATE TABLE EMPLOYEE
(
  NAME  CHAR(15),
  EMPLOYEE_NUM  CHAR(9) NOT NULL,
  BDATE DATE,
  ADDRESS VARCHAR(30),
  GENDER CHAR(1),
  SALARY  INT,
  SUPER_NUM CHAR(9),
  DEPT_NUM INT,
  PRIMARY KEY (EMPLOYEE_NUM)
);

CREATE TABLE PROJECT
(
  NAME  CHAR(15)  NOT NULL,
  PROJECT_NUM CHAR(9)  NOT NULL,
  LOCATION  VARCHAR(30),
  DEPT_NUM  INT,
  PRIMARY KEY (NAME, PROJECT_NUM)
);

CREATE TABLE WORKS_ON
(
  EMPLOYEE_NUM  CHAR(9)  NOT NULL,
  PROJECT_NUM INT NOT NULL,
  HOURS DECIMAL(2,1),
  PRIMARY KEY (EMPLOYEE_NUM, PROJECT_NUM)
);
