/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.databaseGUI;

import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Locale;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import my.databaseGUI.Connector;

/**
 *
 * @author Hunter
 */


public class Interface extends javax.swing.JFrame {

    Connector connector = new Connector();
    public static Object[]  selectedVehicle;
    public static Object[] selectedCustomer;
    public static int selectedRowV;
    public static int selectedRowC;
    
    
   
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        nameInputField = new javax.swing.JTextField();
        areaCode = new javax.swing.JTextField();
        phoneMid = new javax.swing.JTextField();
        phoneLast = new javax.swing.JTextField();
        hyphen1 = new javax.swing.JLabel();
        hyphen2 = new javax.swing.JLabel();
        customerPrompt = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        vehiclePanel = new javax.swing.JPanel();
        vehiclePrompt = new javax.swing.JLabel();
        vinLabel = new javax.swing.JLabel();
        descriptLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        categLabel = new javax.swing.JLabel();
        vinInputField = new javax.swing.JTextField();
        descriptInputField = new javax.swing.JTextField();
        yearInputField = new javax.swing.JTextField();
        typeInputField = new javax.swing.JTextField();
        categInputField = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        rentalPanel = new javax.swing.JPanel();
        rental_Prompt = new javax.swing.JLabel();
        rental_TypeLabel = new javax.swing.JLabel();
        rental_CategLabel = new javax.swing.JLabel();
        rental_dateLabel = new javax.swing.JLabel();
        rental_typeInputField = new javax.swing.JTextField();
        rental_categLabel = new javax.swing.JTextField();
        rental_date1Label = new javax.swing.JTextField();
        rental_date2Label = new javax.swing.JTextField();
        rental_enter = new javax.swing.JButton();
        availablePrompt = new javax.swing.JLabel();
        available_tablePanel = new javax.swing.JScrollPane();
        available_table = new javax.swing.JTable();
        rental_date_TO_label = new javax.swing.JLabel();
        rental_paymentDateLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rental_Searchbtn = new javax.swing.JButton();
        rental_accountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rental_accountTable = new javax.swing.JTable();
        orderDate_label_rental = new javax.swing.JLabel();
        orderDate_inputField = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        qty_combo = new javax.swing.JComboBox<>();
        payment_combo = new javax.swing.JComboBox<>();
        rental_rentalType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        returnsPanel = new javax.swing.JPanel();
        returns_prompt = new javax.swing.JLabel();
        returns_returnDatePrompt = new javax.swing.JLabel();
        returns_custPrompt = new javax.swing.JLabel();
        returns_VINPrompt = new javax.swing.JLabel();
        returns_retDateInputField = new javax.swing.JTextField();
        returns_custInputField = new javax.swing.JTextField();
        returns_VINInputField = new javax.swing.JTextField();
        returns_enter = new javax.swing.JButton();
        returns_amountDUE_prompt = new javax.swing.JLabel();
        amountDuePanel = new javax.swing.JScrollPane();
        amountDueTable = new javax.swing.JTable();
        viewPanel = new javax.swing.JPanel();
        search_view_prompt = new javax.swing.JLabel();
        custID_searchPrompt = new javax.swing.JLabel();
        search_custID_inputfield = new javax.swing.JTextField();
        custName_searchPrompt = new javax.swing.JLabel();
        search_custName_inputfield = new javax.swing.JTextField();
        view_vinLabel = new javax.swing.JLabel();
        view_vinInputField = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        search_results_panel = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        results_Label = new javax.swing.JLabel();
        view_balanceLabel = new javax.swing.JLabel();
        view_startDateLabel = new javax.swing.JLabel();
        view_typeLabel = new javax.swing.JLabel();
        view_categoryLabel = new javax.swing.JLabel();
        balance_combo = new javax.swing.JComboBox<>();
        start_combo = new javax.swing.JComboBox<>();
        type_combo = new javax.swing.JComboBox<>();
        categ_combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSE 3330 Project 2 GUI");

        nameLabel.setText("Customer Name:");

        phoneLabel.setText("Phone Number:");

        nameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputFieldActionPerformed(evt);
            }
        });

        hyphen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hyphen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hyphen1.setText("-");

        hyphen2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hyphen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hyphen2.setText("-");

        customerPrompt.setText("ENTER CUSTOMER INFORMATION");

        submitButton.setBackground(new java.awt.Color(154, 171, 241));
        submitButton.setText("Enter");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton)
                    .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(customerPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(customerPanelLayout.createSequentialGroup()
                            .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(customerPanelLayout.createSequentialGroup()
                                    .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)
                                    .addComponent(hyphen1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(phoneMid, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hyphen2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(phoneLast))
                                .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(customerPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneMid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hyphen2)
                    .addComponent(hyphen1))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer", customerPanel);

        vehiclePrompt.setText("ENTER VEHICLE INFORMATION");

        vinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vinLabel.setText("VIN:");

        descriptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptLabel.setText("Description:");

        yearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yearLabel.setText("Year:");

        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeLabel.setText("Type:");

        categLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categLabel.setText("Category:");

        vinInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinInputFieldActionPerformed(evt);
            }
        });

        enter.setBackground(new java.awt.Color(154, 171, 241));
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehiclePanelLayout = new javax.swing.GroupLayout(vehiclePanel);
        vehiclePanel.setLayout(vehiclePanelLayout);
        vehiclePanelLayout.setHorizontalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(categLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descriptLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(vinLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vinInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(vehiclePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vehiclePanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(enter)))
                .addContainerGap(497, Short.MAX_VALUE))
        );
        vehiclePanelLayout.setVerticalGroup(
            vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiclePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(vehiclePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vinInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(enter)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vehicle", vehiclePanel);

        rental_Prompt.setText("ENTER RENTAL INFORMATION");

        rental_TypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rental_TypeLabel.setText("Type:");

        rental_CategLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rental_CategLabel.setText("Category:");

        rental_dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rental_dateLabel.setText("Dates:");

        rental_categLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_categLabelActionPerformed(evt);
            }
        });

        rental_enter.setBackground(new java.awt.Color(154, 171, 241));
        rental_enter.setText("Enter");
        rental_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_enterActionPerformed(evt);
            }
        });

        availablePrompt.setText("AVAILABLE RENTALS:");

        available_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VehicleID", "Description", "Year", "Type", "Category"
            }
        ));
        available_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                available_tableMouseClicked(evt);
            }
        });
        available_tablePanel.setViewportView(available_table);

        rental_date_TO_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rental_date_TO_label.setText("TO");

        rental_paymentDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rental_paymentDateLabel.setText("Payment Date:");

        rental_Searchbtn.setBackground(new java.awt.Color(154, 171, 241));
        rental_Searchbtn.setText("SEARCH");
        rental_Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rental_SearchbtnActionPerformed(evt);
            }
        });

        rental_accountLabel.setText("ACCOUNTS");

        rental_accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustID", "Name", "Phone"
            }
        ));
        rental_accountTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rental_accountTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rental_accountTable);

        orderDate_label_rental.setText("Order Date");

        qtyLabel.setText("Quantitiy:");

        qty_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        payment_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Return Date" }));

        rental_rentalType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly" }));

        jLabel1.setText("Rental Type:");

        javax.swing.GroupLayout rentalPanelLayout = new javax.swing.GroupLayout(rentalPanel);
        rentalPanel.setLayout(rentalPanelLayout);
        rentalPanelLayout.setHorizontalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rental_Prompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(rental_dateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rental_TypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rental_CategLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rental_typeInputField)
                                    .addComponent(rental_categLabel)
                                    .addGroup(rentalPanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(rental_date1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rental_date_TO_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rental_date2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(35, 87, Short.MAX_VALUE))
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                .addComponent(rental_accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentalPanelLayout.createSequentialGroup()
                                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(rentalPanelLayout.createSequentialGroup()
                                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(rentalPanelLayout.createSequentialGroup()
                                                .addComponent(qtyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentalPanelLayout.createSequentialGroup()
                                                .addComponent(rental_paymentDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(qty_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(payment_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(45, 45, 45)
                                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rental_rentalType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))
                                    .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rental_Searchbtn, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rentalPanelLayout.createSequentialGroup()
                                            .addComponent(orderDate_label_rental, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(orderDate_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12))
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(availablePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(available_tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rental_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentalPanelLayout.setVerticalGroup(
            rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentalPanelLayout.createSequentialGroup()
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(rental_Prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rentalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(availablePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentalPanelLayout.createSequentialGroup()
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rental_TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_typeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rental_CategLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_categLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rental_dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_date1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_date2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_date_TO_label))
                        .addGap(1, 1, 1)
                        .addComponent(rental_Searchbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(rental_accountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderDate_label_rental)
                            .addComponent(orderDate_inputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rental_paymentDateLabel)
                            .addComponent(payment_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(rentalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyLabel)
                            .addComponent(qty_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rental_rentalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(available_tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rental_enter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rental", rentalPanel);

        returns_prompt.setText("RETURN INFORMATION");

        returns_returnDatePrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns_returnDatePrompt.setText("Return Date:");

        returns_custPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns_custPrompt.setText("Customer Name:");

        returns_VINPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns_VINPrompt.setText("VIN:");

        returns_enter.setBackground(new java.awt.Color(154, 171, 241));
        returns_enter.setText("Enter");
        returns_enter.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                returns_enterComponentShown(evt);
            }
        });
        returns_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returns_enterActionPerformed(evt);
            }
        });

        returns_amountDUE_prompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returns_amountDUE_prompt.setText("AMOUNT DUE:");

        amountDueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        amountDuePanel.setViewportView(amountDueTable);

        javax.swing.GroupLayout returnsPanelLayout = new javax.swing.GroupLayout(returnsPanel);
        returnsPanel.setLayout(returnsPanelLayout);
        returnsPanelLayout.setHorizontalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnsPanelLayout.createSequentialGroup()
                .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnsPanelLayout.createSequentialGroup()
                        .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnsPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(returns_amountDUE_prompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(returns_prompt, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(returns_returnDatePrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(returns_custPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(returns_VINPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(returnsPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(returns_enter)))
                        .addGap(18, 18, 18)
                        .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(returns_retDateInputField)
                            .addComponent(returns_custInputField)
                            .addComponent(returns_VINInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)))
                    .addGroup(returnsPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(amountDuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(405, Short.MAX_VALUE))
        );
        returnsPanelLayout.setVerticalGroup(
            returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnsPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(returns_prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returns_returnDatePrompt)
                    .addComponent(returns_retDateInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returns_custPrompt)
                    .addComponent(returns_custInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(returnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returns_VINPrompt)
                    .addComponent(returns_VINInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returns_enter)
                .addGap(25, 25, 25)
                .addComponent(returns_amountDUE_prompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountDuePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Returns", returnsPanel);

        viewPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        search_view_prompt.setText("SEARCH INFO");

        custID_searchPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custID_searchPrompt.setText("CUSTOMER ID:");

        custName_searchPrompt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custName_searchPrompt.setText("CUSTOMER NAME:");

        view_vinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        view_vinLabel.setText("VIN:");

        search_button.setBackground(new java.awt.Color(154, 171, 241));
        search_button.setText("SEARCH");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderDate", "StartDate", "ReturnDate", "TotalDays", "VIN", "Vehicle", "Type", "Category", "CustomerID", "CustomerName", "OrderAmount", "RentalBalance"
            }
        ));
        search_results_panel.setViewportView(search_table);

        results_Label.setText("RESULTS");

        view_balanceLabel.setText("Balance:");

        view_startDateLabel.setText("Start Date:");

        view_typeLabel.setText("Type:");

        view_categoryLabel.setText("Category:");

        balance_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "ASC", "DESC" }));

        start_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "ASC", "DESC" }));

        type_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Compact", "Medium", "Large", "SUV", "Truck", "Van" }));

        categ_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Basic", "Luxury" }));

        javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(viewPanel);
        viewPanel.setLayout(viewPanelLayout);
        viewPanelLayout.setHorizontalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(search_results_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(viewPanelLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPanelLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(custID_searchPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(search_custID_inputfield, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(search_view_prompt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(viewPanelLayout.createSequentialGroup()
                                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(view_vinLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(custName_searchPrompt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                        .addGroup(viewPanelLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(search_button)))
                                    .addGap(16, 16, 16)
                                    .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(search_custName_inputfield, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(view_vinInputField)))))
                        .addComponent(results_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewPanelLayout.createSequentialGroup()
                        .addComponent(view_balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balance_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(view_startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(view_typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(view_categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categ_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        viewPanelLayout.setVerticalGroup(
            viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(search_view_prompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custID_searchPrompt)
                    .addComponent(search_custID_inputfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custName_searchPrompt)
                    .addComponent(search_custName_inputfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_vinLabel)
                    .addComponent(view_vinInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(search_button)
                .addGap(7, 7, 7)
                .addGroup(viewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_balanceLabel)
                    .addComponent(view_startDateLabel)
                    .addComponent(view_typeLabel)
                    .addComponent(view_categoryLabel)
                    .addComponent(balance_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categ_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(results_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_results_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", viewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void nameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputFieldActionPerformed

    private void vinInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vinInputFieldActionPerformed

    private void rental_categLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_categLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rental_categLabelActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try {
            String name = nameInputField.getText();
            String phone_areaCode = areaCode.getText();
            String mid = phoneMid.getText();
            String last = phoneLast.getText();
            connector.newCustomer(name, phone_areaCode, mid, last);
        } catch (Exception e) {
            System.out.println(e);
        }
        
          
    }//GEN-LAST:event_submitButtonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        // TODO add your handling code here:
        // get info from text fields and filters from combo boxes
        // call connector and get values
        // if all empty, get all from view
        // print out results
        
        ArrayList<View> viewList;
        DefaultTableModel model = (DefaultTableModel) search_table.getModel();
        model.setRowCount(0);
        Object[] row = new Object[12];
        
        try {
            String custID = search_custID_inputfield.getText();
            //System.out.println(custID);
            String name = search_custName_inputfield.getText();
            //System.out.println(name);
            String vin = view_vinInputField.getText();
            //System.out.println(vin);
            String balance = balance_combo.getSelectedItem().toString();
            //System.out.println(balance);
            String startDate = start_combo.getSelectedItem().toString();
            //System.out.println(startDate);
            String type = type_combo.getSelectedItem().toString();
            //System.out.println(type);
            String category = categ_combo.getSelectedItem().toString();
            //System.out.println(category);
            
           if (custID.trim().length() == 0 && name.trim().length() == 0 && vin.trim().length() == 0 && balance == "--" && startDate == "--" && type == "--" && category == "--")
            {
                viewList = connector.getNoFilter_rentalView();
                for (int i = 0; i<viewList.size(); i++)
                {
                    row[0]=viewList.get(i).getOrderDate();
                    row[1]=viewList.get(i).getStartDate();
                    row[2]=viewList.get(i).getReturnDate();
                    row[3]=viewList.get(i).getTotalDays();
                    row[4]=viewList.get(i).getVin();
                    row[5]=viewList.get(i).getVehicle();
                    row[6]=viewList.get(i).getType();
                    row[7]=viewList.get(i).getCategory();
                    row[8]=viewList.get(i).getCustID();
                    row[9]=viewList.get(i).getName();
                    row[10]=viewList.get(i).getOrderAmount();
                    row[11]=viewList.get(i).getRentalBalance();
                    model.addRow(row);
                    
                }
                
            }
            else 
            {
                viewList = connector.getByFilter_rentalView(custID, name, vin, balance, startDate, type, category);
                for (int i = 0; i<viewList.size(); i++)
                {
                    row[0]=viewList.get(i).getOrderDate();
                    row[1]=viewList.get(i).getStartDate();
                    row[2]=viewList.get(i).getReturnDate();
                    row[3]=viewList.get(i).getTotalDays();
                    row[4]=viewList.get(i).getVin();
                    row[5]=viewList.get(i).getVehicle();
                    row[6]=viewList.get(i).getType();
                    row[7]=viewList.get(i).getCategory();
                    row[8]=viewList.get(i).getCustID();
                    row[9]=viewList.get(i).getName();
                    row[10]=viewList.get(i).getOrderAmount();
                    row[11]=viewList.get(i).getRentalBalance();
                    model.addRow(row);
                    
                }
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        try {
            String vin = vinInputField.getText();
            String description = descriptInputField.getText();
            String year = yearInputField.getText();
            String type = typeInputField.getText();
            String category = categInputField.getText();
            
            connector.newVehicle(vin, description, year, type, category);
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_enterActionPerformed

    private void returns_enterComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_returns_enterComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_returns_enterComponentShown

    private void returns_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returns_enterActionPerformed
        // TODO add your handling code here:
        try {
            
            DefaultTableModel model = (DefaultTableModel) amountDueTable.getModel();
            model.setNumRows(0);
            model.setColumnCount(0);
            String vin = returns_VINInputField.getText();
            String customer = returns_custInputField.getText();
            String date = returns_retDateInputField.getText();
            String balance = connector.returnRental(date, customer, vin);
            model.addColumn("Balance Remaining");
            model.addRow(new Object[]{balance});
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_returns_enterActionPerformed

    private void rental_SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_SearchbtnActionPerformed
        // TODO add your handling code here:
        ArrayList<Vehicle> vehicleList;
        ArrayList<Customer> customerList;
        DefaultTableModel model = (DefaultTableModel) available_table.getModel();
        DefaultTableModel model1 = (DefaultTableModel) rental_accountTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[5];
        Object[] row1 = new Object[3];
        
        try {
            String type = rental_typeInputField.getText();
            String category = rental_categLabel.getText();
            String startDate = rental_date1Label.getText();
            String returnDate = rental_date2Label.getText();
            
            vehicleList = connector.searchRentals(type, category, startDate, returnDate);
            for (int i = 0; i<vehicleList.size(); i++)
            {
                row[0] = vehicleList.get(i).getVin();
                row[1] = vehicleList.get(i).getDescription();
                row[2] = vehicleList.get(i).getYear();
                row[3] = vehicleList.get(i).getType();
                row[4] = vehicleList.get(i).getCategory();
                model.addRow(row);
                    
            }
            customerList = connector.getCustomer();
            for (int i = 0; i<vehicleList.size(); i++)
            {
                row1[0] = customerList.get(i).getID();
                row1[1] = customerList.get(i).getName();
                row1[2] = customerList.get(i).getPhone();
                model1.addRow(row1);
                    
            }
            
        } catch (Exception e) {
            System.out.println(e);
        }
            
        
        
    }//GEN-LAST:event_rental_SearchbtnActionPerformed

    private void available_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_available_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) available_table.getModel();
        selectedRowV = available_table.getSelectedRow();
        selectedVehicle = model.getDataVector().toArray();
        
    }//GEN-LAST:event_available_tableMouseClicked

    private void rental_accountTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rental_accountTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) rental_accountTable.getModel();
        selectedRowC = rental_accountTable.getSelectedRow();
        selectedCustomer = model.getDataVector().toArray();
        
    }//GEN-LAST:event_rental_accountTableMouseClicked

    private void rental_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rental_enterActionPerformed
        // TODO add your handling code here:
        
        try {
            
            String startDate = rental_date1Label.getText();
            String returnDate = rental_date2Label.getText();
            
            LocalDate date1 = LocalDate.parse(startDate);
            LocalDate date2 = LocalDate.parse(returnDate);
            
            long daysBetween = ChronoUnit.DAYS.between(date1, date2);
            String days =daysBetween + "";
            
            String[] customerRow;
            customerRow = selectedCustomer[selectedRowC].toString().substring(1, selectedCustomer[selectedRowC].toString().length()-1).split("\\, ");
            String custID = customerRow[0];
            System.out.println(custID);
            String[] vehicleRow;
            vehicleRow = selectedVehicle[selectedRowV].toString().substring(1, selectedVehicle[selectedRowV].toString().length()-1).split("\\, ");
            String vin = vehicleRow[0];
            System.out.println(vin);
            String orderDate = orderDate_inputField.getText(); 
            String rentalType = rental_rentalType.getSelectedItem().toString();
            String qty = qty_combo.getSelectedItem().toString();
            String choice = payment_combo.getSelectedItem().toString();
            String paymentDate;
            String returned;
            if (choice == "Today")
            {
                paymentDate = rental_date1Label.getText();
                returned = "1";
            }
            else
            {
                paymentDate = rental_date2Label.getText();
                returned = "0";
            }
           
            connector.insertRental(custID, vin, startDate, orderDate, rentalType, qty, returnDate, paymentDate, returned, days);
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
        
        
    }//GEN-LAST:event_rental_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane amountDuePanel;
    private javax.swing.JTable amountDueTable;
    private javax.swing.JTextField areaCode;
    private javax.swing.JLabel availablePrompt;
    private javax.swing.JTable available_table;
    private javax.swing.JScrollPane available_tablePanel;
    private javax.swing.JComboBox<String> balance_combo;
    private javax.swing.JTextField categInputField;
    private javax.swing.JLabel categLabel;
    private javax.swing.JComboBox<String> categ_combo;
    private javax.swing.JLabel custID_searchPrompt;
    private javax.swing.JLabel custName_searchPrompt;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel customerPrompt;
    private javax.swing.JTextField descriptInputField;
    private javax.swing.JLabel descriptLabel;
    private javax.swing.JButton enter;
    private javax.swing.JLabel hyphen1;
    private javax.swing.JLabel hyphen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameInputField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField orderDate_inputField;
    private javax.swing.JLabel orderDate_label_rental;
    private javax.swing.JComboBox<String> payment_combo;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneLast;
    private javax.swing.JTextField phoneMid;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JComboBox<String> qty_combo;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JLabel rental_CategLabel;
    private javax.swing.JLabel rental_Prompt;
    private javax.swing.JButton rental_Searchbtn;
    private javax.swing.JLabel rental_TypeLabel;
    private javax.swing.JLabel rental_accountLabel;
    private javax.swing.JTable rental_accountTable;
    private javax.swing.JTextField rental_categLabel;
    private javax.swing.JTextField rental_date1Label;
    private javax.swing.JTextField rental_date2Label;
    private javax.swing.JLabel rental_dateLabel;
    private javax.swing.JLabel rental_date_TO_label;
    private javax.swing.JButton rental_enter;
    private javax.swing.JLabel rental_paymentDateLabel;
    private javax.swing.JComboBox<String> rental_rentalType;
    private javax.swing.JTextField rental_typeInputField;
    private javax.swing.JLabel results_Label;
    private javax.swing.JPanel returnsPanel;
    private javax.swing.JTextField returns_VINInputField;
    private javax.swing.JLabel returns_VINPrompt;
    private javax.swing.JLabel returns_amountDUE_prompt;
    private javax.swing.JTextField returns_custInputField;
    private javax.swing.JLabel returns_custPrompt;
    private javax.swing.JButton returns_enter;
    private javax.swing.JLabel returns_prompt;
    private javax.swing.JTextField returns_retDateInputField;
    private javax.swing.JLabel returns_returnDatePrompt;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_custID_inputfield;
    private javax.swing.JTextField search_custName_inputfield;
    private javax.swing.JScrollPane search_results_panel;
    private javax.swing.JTable search_table;
    private javax.swing.JLabel search_view_prompt;
    private javax.swing.JComboBox<String> start_combo;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField typeInputField;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JComboBox<String> type_combo;
    private javax.swing.JPanel vehiclePanel;
    private javax.swing.JLabel vehiclePrompt;
    private javax.swing.JPanel viewPanel;
    private javax.swing.JLabel view_balanceLabel;
    private javax.swing.JLabel view_categoryLabel;
    private javax.swing.JLabel view_startDateLabel;
    private javax.swing.JLabel view_typeLabel;
    private javax.swing.JTextField view_vinInputField;
    private javax.swing.JLabel view_vinLabel;
    private javax.swing.JTextField vinInputField;
    private javax.swing.JLabel vinLabel;
    private javax.swing.JTextField yearInputField;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
